version: '3'

networks:
  local_network:
    external: true

services:

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - local_network
  
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - local_network

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
    networks:
      - local_network